using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using BeatEmUp;
using UnityEditor;
using UnityEngine;
using Object=UnityEngine.Object;
[InitializeOnLoad]
public static class PrefectValidation
{
    const string Pending="BeatEmUp.PrefectValidation";
    static readonly List<Object> temporary=new List<Object>();static readonly List<string> results=new List<string>();
    static ComboController player;static EnemyCombat enemy;static PrefectSupport support;static StageFlowController flow;static CombatClock clock;
    static PrefectValidation(){EditorApplication.update+=Poll;}
    [MenuItem("Beat Em Up/Enemies/Validate Prefect (Play Mode)")]
    public static void Run(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)return;SessionState.SetBool(Pending,true);EditorApplication.EnterPlaymode();}
    static void Poll(){
        if(!EditorApplication.isCompiling&&!EditorApplication.isPlayingOrWillChangePlaymode&&File.Exists("Temp/PrefectValidation.request")){try{File.Delete("Temp/PrefectValidation.request");}catch(IOException){return;}Run();return;}
        if(!SessionState.GetBool(Pending,false)||!EditorApplication.isPlaying||EditorApplication.isCompiling)return;SessionState.SetBool(Pending,false);results.Clear();
        try{foreach(var f in Object.FindObjectsByType<StageFlowController>(FindObjectsSortMode.None))f.enabled=false;foreach(var f in Object.FindObjectsByType<StageFraming>(FindObjectsSortMode.None))f.enabled=false;foreach(var m in Object.FindObjectsByType<CharacterMotor>(FindObjectsSortMode.None))m.gameObject.SetActive(false);foreach(var w in Object.FindObjectsByType<CombatWall>(FindObjectsSortMode.None))w.gameObject.SetActive(false);clock=Object.FindFirstObjectByType<CombatClock>();clock.enabled=false;clock.combatFPS=60;
            Calls();Caps();Push();Retreat();AI();results.Add("NOTE: Separate online peers were not launched. StageFlow authority guard, enemy/sprite catalog and existing spawn snapshots inspected.");Debug.Log("PREFECT VALIDATION PASSED: "+results.Count+" results");
        }catch(Exception e){results.Add("FAIL: "+e);Debug.LogException(e);}finally{File.WriteAllLines("Documentation/PrefectValidationResults.txt",results);Clear();EditorApplication.ExitPlaymode();}
    }
    static T Keep<T>(T o) where T:Object{temporary.Add(o);return o;}
    static void Clear(){foreach(var o in temporary.ToArray())if(o)Object.DestroyImmediate(o);temporary.Clear();}
    static void Check(bool p,string label){if(!p)throw new Exception(label);results.Add("PASS: "+label);}
    static void Step(int n=1){for(int i=0;i<n;i++){Physics2D.SyncTransforms();clock.StepFrame();flow.Tick(CombatClock.FrameSeconds);}}
    static void Until(Func<bool> p,string label,int max=700){for(int i=0;i<max&&!p();i++)Step();Check(p(),label);}
    static void Fixture(Vector2 position,bool ai=false,int cap=8,int prefects=1){
        Clear();player=Keep(Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(ComboTrackingSetup.PlayerPath))).GetComponent<ComboController>();player.GetComponent<PlayerCombatInput>().enabled=false;player.health.SafeStageProtection=false;player.health.Restore();
        var level=Keep(Object.Instantiate(AssetDatabase.LoadAssetAtPath<LevelDefinition>(HauntedLevelBuilder.LevelPath)));var stage=level.stages.First(s=>!s.IsSafeStage&&s.backgroundSprite&&s.floorSprite);level.stages=new List<StageSegmentDefinition>{stage};stage.movementMin=new Vector2(-6,-2);stage.movementMax=new Vector2(6,2);stage.playerEntryPoint=position;stage.playerExitPoint=new Vector2(5.8f,1.8f);stage.rewardAfterClear=StageReward.None;stage.maxActiveEnemies=12;stage.completionMode=StageCompletion.ClearEncounters;
        stage.encounters=new List<EncounterDefinition>{new EncounterDefinition{encounterId="Prefect test",trigger=EncounterTrigger.StageEnter,maxActiveEnemies=cap,waves=new List<WaveDefinition>{new WaveDefinition{enemySpawns=new List<EnemySpawnDefinition>{new EnemySpawnDefinition{prefab=AssetDatabase.LoadAssetAtPath<GameObject>(PrefectSetup.PrefabPath),count=prefects,spawnPoints=new List<Vector2>{Vector2.zero,new Vector2(0,.8f),new Vector2(-5,-1),new Vector2(5,1)}}}}}}};
        flow=Keep(new GameObject("Prefect validation flow")).AddComponent<StageFlowController>();flow.enabled=false;flow.showHud=false;flow.level=level;flow.player=player.motor;flow.EnterStage(0);flow.Tick(CombatClock.FrameSeconds);enemy=flow.LivingEnemies.First().GetComponent<EnemyCombat>();support=enemy.GetComponent<PrefectSupport>();foreach(var h in flow.LivingEnemies){var b=h.GetComponent<EnemyCombat>();b.enabled=ai;if(ai)b.RefreshAI();}Check(string.IsNullOrEmpty(flow.Failure),"Real encounter fixture starts without spawn errors");
    }
    static void StartCall(){Check(enemy.attackPlayer.Play(support.callBackup),"Frame-data backup call begins");}
    static void StopRushers(){foreach(var h in flow.LivingEnemies.Where(h=>h.GetComponent<EnemyCombat>().role==EnemyRole.Rusher))h.GetComponent<EnemyCombat>().enabled=false;}
    static void Hit(){enemy.GetComponentInChildren<CombatHurtbox>().Receive(new AttackHitboxData{damage=1,hitstunFrames=18,knockback=0},1,player.motor);}
    static void Calls(){
        Fixture(new Vector2(4,0));StartCall();Step(23);Check(flow.LivingEnemies.Count()==1&&support.CallsActivated==0&&enemy.motor.IsGrounded&&enemy.transform.position==Vector3.zero,"24-frame telegraph stays stationary and cannot summon early");Check(enemy.motor.sprite.sprite.name.Contains("Whistle_Call"),"Existing call / authority sprites play during startup");Step();Check(support.CallsActivated==1&&support.LastCallSpawned==2&&flow.LivingEnemies.Count()==3,"CallBackup24 spawns exactly2 tracked Rushers");
        var rushers=flow.LivingEnemies.Where(h=>h!=enemy.reaction.health).ToArray();Check(rushers.All(h=>h.GetComponent<EnemyCombat>().role==EnemyRole.Rusher&&h.GetComponent<EnemyCombat>().enabled&&!h.GetComponent<EnemyCombat>().passiveTrainingDummy&&h.GetComponent<EnemyCombat>().aiProfile),"Backup uses only existing typed Rusher prefab / normal AI");Check(rushers.All(h=>Vector2.Distance(h.transform.position,player.transform.position)>=1.25f&&Vector2.Distance(h.transform.position,enemy.transform.position)>=.75f),"Backup does not spawn inside player or Prefect");Check(rushers.All(h=>h.GetComponent<CharacterMotor>().arenaMin==player.motor.arenaMin&&h.GetComponent<CharacterMotor>().arenaMax==player.motor.arenaMax),"Spawned motors inherit same room bounds");StopRushers();Step(17);Check(enemy.attackPlayer.CurrentFrame==41,"Backup recovery retained through41");Step();Check(!enemy.attackPlayer.CurrentAttack&&support.CallsActivated==1,"Single cast cannot replay backup event");enemy.reaction.health.Damage(999);flow.Tick(.02f);Check(!flow.EncountersComplete&&!flow.CompletionSatisfied,"Prefect death does not clear encounter while backup lives");foreach(var h in rushers)h.Damage(999);flow.Tick(.02f);Check(flow.EncountersComplete&&flow.CompletionSatisfied,"Defeated backup completes original wave / encounter without stuck tracking");
        foreach(int frame in new[]{0,12,23}){Fixture(new Vector2(4,0));StartCall();Step(frame);Hit();Step(80);Check(support.CallsActivated==0&&flow.LivingEnemies.Count()==1&&!enemy.attackPlayer.CurrentAttack,"Interrupt before spawn leaves no delayed summons, frame "+frame);}
        Fixture(new Vector2(4,0));support.rusherPrefab=AssetDatabase.LoadAssetAtPath<GameObject>(AmbusherSetup.PrefabPath);StartCall();Step(24);Check(support.LastCallSpawned==0&&flow.LivingEnemies.Count()==1,"Misconfigured non-Rusher prefab is rejected by authoritative spawn API");
        Fixture(new Vector2(4,0));var wall=Keep(new GameObject("Backup spawn wall"));wall.transform.position=new Vector2(-5,-1);wall.AddComponent<BoxCollider2D>().size=Vector2.one;wall.AddComponent<CombatWall>();StartCall();Step(24);Check(support.LastCallSpawned==2&&flow.LivingEnemies.Where(h=>h!=enemy.reaction.health).All(h=>Vector2.Distance(h.transform.position,wall.transform.position)>.6f),"Blocked authored spawn point skipped for valid entrance/perimeter points");
        Fixture(new Vector2(4,0));StartCall();CombatClock.SetPaused(enemy.gameObject,true);Step(50);Check(support.CallsActivated==0,"Global combat pause cannot activate summon event");CombatClock.SetPaused(enemy.gameObject,false);
    }
    static void Caps(){
        Fixture(new Vector2(2.5f,0));var zone=flow.CurrentStage.encounters[0];zone.useCombatBounds=true;zone.combatBounds=new Rect(-3,-1,6,2);flow.Tick(.02f);StartCall();Step(24);Check(support.LastCallSpawned==2 && flow.LivingEnemies.All(h=>h.GetComponent<CharacterMotor>().arenaMin==new Vector2(-3,-1) && h.GetComponent<CharacterMotor>().arenaMax==new Vector2(3,1) && zone.combatBounds.Contains(h.transform.position)),"Backup obeys active combat-zone bounds and tracking");
        Fixture(new Vector2(4,0),cap:2);StartCall();Step(24);Check(support.LastCallSpawned==1&&flow.LivingEnemies.Count()==2,"One remaining encounter slot spawns only one Rusher");
        Fixture(new Vector2(4,0),cap:1);Check(!support.CallReady&&support.EnemySlots==0,"Full encounter prevents AI backup eligibility");StartCall();Step(24);Check(support.LastCallSpawned==0&&flow.LivingEnemies.Count()==1,"Full encounter rejects even an externally started backup cast");
        Fixture(new Vector2(4,0),cap:3,prefects:2);var second=flow.LivingEnemies.Last().GetComponent<EnemyCombat>();StartCall();second.attackPlayer.Play(second.GetComponent<PrefectSupport>().callBackup);Step(24);Check(flow.LivingEnemies.Count()==3&&support.LastCallSpawned+second.GetComponent<PrefectSupport>().LastCallSpawned==1,"Simultaneous Prefects share atomic encounter cap");
        Fixture(new Vector2(4,0),cap:8,prefects:2);flow.CurrentStage.maxActiveEnemies=3;var secondBrain=flow.LivingEnemies.Last().GetComponent<EnemyCombat>();StartCall();secondBrain.attackPlayer.Play(secondBrain.GetComponent<PrefectSupport>().callBackup);Step(24);Check(flow.LivingEnemies.Count()==3,"Room-wide cap also restricts backup below encounter cap");
        Fixture(new Vector2(4,0),cap:3,prefects:5);Check(flow.LivingEnemies.Count()==3,"Authored wave spawning uses same active cap");flow.LivingEnemies.First().Damage(999);flow.Tick(.02f);Check(flow.LivingEnemies.Count()==3&&flow.StageEnemies.Count()==4,"Pending authored wave waits for slot and resumes after a death");
    }
    static void Push(){
        foreach(int facing in new[]{1,-1}){
            Fixture(new Vector2(.7f*facing,0));enemy.motor.Face(facing);Check(enemy.attackPlayer.Play(support.pushAttack),"Defensive push begins facing "+facing);Step(5);Check(player.health.Current==200&&player.State==CombatState.Idle,"Push has six readable startup frames without damage");Step();Check(player.health.Current==196&&player.State==CombatState.Hitstun&&!player.IsKnockdownState&&player.motor.HorizontalRecoil*facing>5.9f,"Push6 applies low4 damage / normal hitstun / strong outward recoil");Step(3);Step(3);Check(player.health.Current==196&&player.motor.transform.position.x*facing>.7f,"Active frames share one accepted hit and move victim away");Until(()=>!enemy.attackPlayer.CurrentAttack,"Push finishes its punishable recovery");Until(()=>player.State==CombatState.Idle,"Short hitstun returns control without knockdown");
        }
        Fixture(new Vector2(.55f,.3f));enemy.attackPlayer.Play(support.pushAttack);Step(6);Step(4);Check(player.motor.transform.position.y>.3f&&!player.IsKnockdownState,"Outward recoil includes valid XY depth component");
        foreach(var point in new[]{new Vector2(-1,0),new Vector2(.7f,.9f),new Vector2(2,0)}){Fixture(point);enemy.motor.Face(1);enemy.attackPlayer.Play(support.pushAttack);Step(9);Check(player.health.Current==200,"Push only threatens local forward box/lane at "+point);}
        Fixture(new Vector2(.7f,0));var other=Keep(Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(ComboTrackingSetup.PlayerPath))).GetComponent<ComboController>();other.GetComponent<PlayerCombatInput>().enabled=false;other.health.Restore();other.motor.ResetForStage(new Vector2(-4,1));enemy.attackPlayer.Play(support.pushAttack);Step(6);Check(player.health.Current==196&&other.health.Current==200,"Push does not globally affect another player outside its box");
        Fixture(new Vector2(.7f,0));player.motor.Face(-1);player.RequestGuard(true);Step(6);enemy.attackPlayer.Play(support.pushAttack);Step(6);Check(player.health.Current==200&&!player.IsKnockdownState,"Normal guard/parry defense path handles defensive push");
    }
    static void Retreat(){
        Fixture(new Vector2(1.8f,.8f),true,1);float distance=support.ThreatDistance;Step(20);Check(support.ThreatDistance>distance&&enemy.transform.position.x<0&&enemy.transform.position.y<0,"Prefect retreats diagonally away from nearby threat");Until(()=>support.ThreatDistance>=3.5f,"Retreat reaches preferred distance");Step(10);var position=enemy.transform.position;Step(40);Check(Vector2.Distance(position,enemy.transform.position)<.01f,"Prefect stops fleeing once preferred distance is reached");
        Fixture(new Vector2(-1,0),true,1);enemy.motor.transform.position=new Vector2(-.1f,0);enemy.motor.arenaMax=new Vector2(.1f,2);var direction=support.RetreatDirection();Check(Mathf.Abs(direction.y)>.5f,"Blocked ideal escape at boundary selects a lane/tangent alternative");Step(40);Check(enemy.transform.position.x<=.1f&&enemy.transform.position.y<=2&&enemy.transform.position.y>=-2,"Retreat stays inside motor/room bounds");
        Fixture(new Vector2(-1.5f,0),true,1);var wall=Keep(new GameObject("Retreat wall"));wall.transform.position=new Vector2(.4f,0);wall.AddComponent<BoxCollider2D>().size=new Vector2(.2f,2);wall.AddComponent<CombatWall>();Physics2D.SyncTransforms();var alternative=support.RetreatDirection();Check(Mathf.Abs(alternative.y)>.1f,"Solid wall makes retreat probe choose another increasing-distance direction");
    }
    static void AI(){
        Fixture(new Vector2(0,.7f),true,1);Step(20);Check(enemy.transform.position.y<0 && !enemy.attackPlayer.CurrentAttack,"Close threat in another lane retreats instead of entering an ineligible push state");
        Fixture(new Vector2(4,0),true);Until(()=>enemy.attackPlayer.CurrentAttack==support.callBackup,"Safe distance / free slots trigger AI backup telegraph");Hit();Check(enemy.AI.Cooldown("CallBackup")>7.9f,"Interrupted call consumes8-second cooldown");Step(100);Check(support.CallsActivated==0,"AI interruption never spawns pending backup later");
        Fixture(new Vector2(.7f,0),true);Until(()=>enemy.attackPlayer.CurrentAttack==support.pushAttack,"Emergency player proximity prioritizes push over long call");Until(()=>!enemy.attackPlayer.CurrentAttack,"AI push recovery completes");Check(enemy.AI.Cooldown("Push")>1.9f,"Push consumes2-second cooldown independently of backup");Step(12);Check(enemy.AI.StateName=="Retreat"||support.ThreatDistance>=support.PreferredDistance,"After push Prefect creates distance rather than immediate shove spam");
        Fixture(new Vector2(4,0),true);Until(()=>support.CallsActivated==1,"AI call reaches frame24");StopRushers();Until(()=>!enemy.attackPlayer.CurrentAttack,"AI call recovery ends");Check(enemy.AI.Cooldown("CallBackup")>7.9f,"Successful call receives8-second cooldown");Step(100);Check(support.CallsActivated==1,"Backup cooldown prevents repeated calls");
        Check(!enemy.aiProfile.Validate().Any(),"Editable Prefect AI states/transitions/choices validate");var catalog=AssetDatabase.LoadAssetAtPath<MultiplayerCatalog>(MultiplayerSetup.CatalogPath);Check(catalog.AttackId(support.callBackup)>=0&&catalog.AttackId(support.pushAttack)>=0,"Call/push assets present in multiplayer catalog");
        Fixture(new Vector2(4,0));StartCall();Step(18);CaptureImage("CallTelegraph");Step(6);StopRushers();CaptureImage("Backup");Fixture(new Vector2(.7f,0));enemy.attackPlayer.Play(support.pushAttack);Step(6);CaptureImage("Push");
    }
    static void CaptureImage(string name){var go=new GameObject("Prefect preview camera");var camera=go.AddComponent<Camera>();camera.enabled=false;camera.orthographic=true;camera.orthographicSize=name=="Backup" ? 3.5f : 2.4f;camera.transform.position=new Vector3(0,1,-10);var rt=new RenderTexture(1280,720,24);camera.targetTexture=rt;var previous=RenderTexture.active;try{camera.Render();RenderTexture.active=rt;var tex=new Texture2D(1280,720,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1280,720),0,0);tex.Apply();Directory.CreateDirectory("Documentation/PrefectPreview");File.WriteAllBytes("Documentation/PrefectPreview/"+name+".png",tex.EncodeToPNG());Object.DestroyImmediate(tex);}finally{RenderTexture.active=previous;Object.DestroyImmediate(rt);Object.DestroyImmediate(go);}}
}
