const fs=require('fs'),path=require('path'),crypto=require('crypto'),sharp=require('sharp');
const scan=require('../HauntedEnemies/scan.cjs');
const root=path.resolve(__dirname,'../..'),dir=path.join(root,'Assets/ArtAssets/Characters/BlueShirtGuy/AirDive');
const job=JSON.parse(fs.readFileSync(path.join(__dirname,'generation.json'))),names=['AirReady','Windup','DiveStart','ActiveDive','Impact','LandingRecovery'];
const template=fs.readFileSync(path.join(root,'Assets/EQ_Rung_BeatEmUp/Sprites/BlueShirtGuy_Walk2_01.png.meta'),'utf8');
const guid=()=>crypto.randomBytes(16).toString('hex');function meta(f,sprite=false,folder=false){if(fs.existsSync(f+'.meta'))return;const text=sprite?template.replace(/^guid: .+$/m,'guid: '+guid()).replace(/spriteID: [a-f0-9]+/,'spriteID: '+guid()):'fileFormatVersion: 2\nguid: '+guid()+'\n'+(folder?'folderAsset: yes\n':'')+'DefaultImporter:\n  externalObjects: {}\n';fs.writeFileSync(f+'.meta',text);}
function isolate(pixels,w,h){const seen=new Uint8Array(w*h),q=new Int32Array(w*h);let best=[];for(let s=0;s<seen.length;s++){if(seen[s]||pixels[s*4+3]<128)continue;let head=0,tail=1;q[0]=s;seen[s]=1;while(head<tail){const p=q[head++],x=p%w,y=Math.floor(p/w);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const xx=x+dx,yy=y+dy;if(xx<0||yy<0||xx>=w||yy>=h)continue;const k=yy*w+xx;if(seen[k]||pixels[k*4+3]<128)continue;seen[k]=1;q[tail++]=k;}}if(tail>best.length)best=Array.from(q.subarray(0,tail));}const keep=new Uint8Array(w*h);for(const p of best)keep[p]=1;for(let p=0;p<keep.length;p++)if(!keep[p])pixels.fill(0,p*4,p*4+4);return pixels;}
async function main(){fs.mkdirSync(dir,{recursive:true});for(let p=dir;p.startsWith(path.join(root,'Assets/ArtAssets/Characters/BlueShirtGuy'));p=path.dirname(p))meta(p,false,true);const source=path.join(dir,'Source.png');if(fs.existsSync(job.source))fs.copyFileSync(job.source,source);meta(source);
const src=await scan(source);const blobs=src.blobs.filter(b=>b.area>4000).sort((a,b)=>a.left-b.left);if(blobs.length!==6)throw Error('Expected six isolated character drawings, got '+blobs.length);
const scale=100/blobs[0].height,frames=[];for(let i=0;i<6;i++){const b=blobs[i],rw=Math.round(b.width*scale),rh=Math.round(b.height*scale);if(rw>152||rh>116)throw Error('Pose clips canvas');const pixels=await sharp(src.data,{raw:{width:src.info.width,height:src.info.height,channels:4}}).extract({left:b.left,top:b.top,width:b.width,height:b.height}).raw().toBuffer();const clean=isolate(pixels,b.width,b.height);const scaled=await sharp(clean,{raw:{width:b.width,height:b.height,channels:4}}).resize(rw,rh,{kernel:'nearest'}).raw().toBuffer();const out=Buffer.alloc(160*128*4),x=Math.floor((160-rw)/2),y=120-rh;for(let yy=0;yy<rh;yy++)for(let xx=0;xx<rw;xx++){const p=(yy*rw+xx)*4,q=((yy+y)*160+xx+x)*4;if(scaled[p+3]<128)continue;out[q]=scaled[p];out[q+1]=scaled[p+1];out[q+2]=scaled[p+2];out[q+3]=255;}const file=path.join(dir,'BlueShirtGuy_AirDive_'+names[i]+'.png');await sharp(out,{raw:{width:160,height:128,channels:4}}).png().toFile(file);meta(file,true);frames.push(out);}
const strip=Buffer.alloc(960*128*4);for(let i=0;i<6;i++)for(let y=0;y<128;y++)frames[i].copy(strip,(y*960+i*160)*4,y*160*4,(y+1)*160*4);await sharp(strip,{raw:{width:960,height:128,channels:4}}).png().toFile(path.join(dir,'BlueShirtGuy_AirDive_Sheet.png'));meta(path.join(dir,'BlueShirtGuy_AirDive_Sheet.png'));
await sharp(Buffer.concat(frames),{raw:{width:160,height:128*6,channels:4,pageHeight:128}}).gif({loop:0,delay:[34,50,34,117,50,117]}).toFile(path.join(dir,'BlueShirtGuy_AirDive_Preview.gif'));meta(path.join(dir,'BlueShirtGuy_AirDive_Preview.gif'));
fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify({poses:names,canvas:[160,128],pixelsPerUnit:100,pivot:[.5,.0625],baseline:120,source:job.source,standingReadyHeight:100,scale},null,2));meta(path.join(dir,'manifest.json'));console.log('Six transparent, aligned head-first sprites exported.');}
main().catch(e=>{console.error(e);process.exitCode=1;});
