// ImageGen draws the art. This script only normalizes and packages the plates.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),sharp=require('sharp');
const root=path.resolve(__dirname,'../..'),art=path.join(root,'Assets/ArtAssets/Environments/HauntedHouse');
const jobs=JSON.parse(fs.readFileSync(path.join(__dirname,'generation.json'))),guid=()=>crypto.randomBytes(16).toString('hex');
const template=fs.readFileSync(path.join(root,'Assets/ArtAssets/Characters/NPCs/ThaiBadBoy/Animations/Idle/ThaiBadBoy_Idle_01.png.meta'),'utf8');
function meta(f,kind='default'){if(fs.existsSync(f+'.meta'))return;let txt='fileFormatVersion: 2\nguid: '+guid()+'\n';if(kind==='sprite')txt=template.replace(/^guid: .+$/m,'guid: '+guid()).replace(/spriteID: [a-f0-9]+/,'spriteID: '+guid()).replace(/spritePivot: \{.+\}/,'spritePivot: {x: 0.5, y: 0.5}').replace(/spriteGenerateFallbackPhysicsShape: 1/,'spriteGenerateFallbackPhysicsShape: 0');else txt+=(kind==='folder'?'folderAsset: yes\n':'')+'DefaultImporter:\n  externalObjects: {}\n';fs.writeFileSync(f+'.meta',txt);}
function mkdir(f){fs.mkdirSync(f,{recursive:true});let p=f;while(p.startsWith(path.join(root,'Assets/ArtAssets/Environments'))){meta(p,'folder');p=path.dirname(p);}}
async function main(){if(jobs.length!==8)throw Error('Expected all eight stages');mkdir(art);const report={builtInImageGen:true,pixelsPerUnit:100,canvas:[720,400],backgroundFraction:.4,floorFraction:.6,stages:[]};const cards=[];
for(let i=0;i<jobs.length;i++){const j=jobs[i],dir=path.join(art,j.id);mkdir(dir);for(const d of ['Source','Background','Floor'])mkdir(path.join(dir,d));const source=path.join(dir,'Source',j.id+'_Source.png');if(fs.existsSync(j.source))fs.copyFileSync(j.source,source);meta(source);const m=await sharp(source).metadata(),split=Math.round(m.height*j.sourceSplit);const entries=[];
for(const [layer,y,height,outHeight]of[['Background',0,split,160],['Floor',split,m.height-split,240]]){const file=path.join(dir,layer,j.id+'_'+layer+'.png');await sharp(source).extract({left:0,top:y,width:m.width,height}).resize(720,outHeight,{kernel:'nearest'}).png().toFile(file);meta(file,'sprite');const actual=await sharp(file).metadata();if(actual.width!==720||actual.height!==outHeight)throw Error('Bad dimensions');entries.push({layer,file:path.relative(root,file).replaceAll('\\','/'),canvas:[720,outHeight],position:[0,layer==='Background'?2.56:.56,0],sortingOrder:layer==='Background'?-100:-90});}
const preview=path.join(dir,j.id+'_Preview.png');await sharp({create:{width:720,height:400,channels:4,background:'#000'}}).composite([{input:path.join(root,entries[0].file),top:0,left:0},{input:path.join(root,entries[1].file),top:160,left:0}]).png().toFile(preview);meta(preview);cards.push({input:preview,left:(i%2)*720,top:Math.floor(i/2)*400});const manifest={id:j.id,name:j.name,sourceSplit:j.sourceSplit,canvas:[720,400],pixelsPerUnit:100,backgroundFraction:.4,floorFraction:.6,plates:entries};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2));meta(path.join(dir,'manifest.json'));report.stages.push(manifest);console.log(j.id+' background + floor exported');}
await sharp({create:{width:1440,height:1600,channels:4,background:'#15131b'}}).composite(cards).png().toFile(path.join(art,'StageOverview.png'));meta(path.join(art,'StageOverview.png'));
fs.writeFileSync(path.join(art,'ArtValidation.json'),JSON.stringify({...report,passed:true,checks:['Eight stages, two plates each','720x160 background and720x240 floor','Reassembled720x400 composition','60 percent open floor band']},null,2));meta(path.join(art,'ArtValidation.json'));
const data=report.stages.map(j=>({id:j.id,name:j.name}));const html=`<!doctype html><html><meta charset="utf-8"><title>Haunted stages gallery</title><style>body{background:#17131c;color:#eee;font:16px system-ui;margin:28px}img{display:block;image-rendering:pixelated;width:min(100%,1080px);margin-top:16px}select,button{font:inherit;padding:10px;background:#342738;color:white;border:1px solid #ac6262}a{color:#ffa7a7;margin:12px}p{max-width:900px}</style><h1>Haunted-house stage art</h1><select id="stage"></select><select id="layer"><option>Preview</option><option>Background</option><option>Floor</option></select><img id="art"><p id="links"></p><p>Eight stages in sequence. Backgrounds are720×160, floors720×240,100PPU,40/60 composition. Scenery plates have no colliders or gameplay logic. These are fixed room segments; edges are not guaranteed to tile seamlessly.</p><script>const stages=${JSON.stringify(data)};const s=document.getElementById('stage'),l=document.getElementById('layer');for(const j of stages){const o=document.createElement('option');o.textContent=j.name;s.append(o);}function show(){const j=stages[s.selectedIndex],kind=l.value;document.getElementById('art').src=j.id+'/'+(kind==='Preview'?'':kind+'/')+j.id+'_'+kind+'.png';document.getElementById('links').innerHTML=['Background','Floor'].map(k=>'<a href="'+j.id+'/'+k+'/'+j.id+'_'+k+'.png">'+k+' PNG</a>').join('');}s.onchange=l.onchange=show;show();</script></html>`;fs.writeFileSync(path.join(art,'Gallery.html'),html);meta(path.join(art,'Gallery.html'));}
main().catch(e=>{console.error(e);process.exitCode=1;});
